### PR TITLE
Grid refinement

### PR DESCRIPTION
**Pull request by nutrik**
Hi Dion,
Could you please take a look at wave propagation case with refined around equator latitude grid?
The case has an issue (when grid refinement and coastal shelfs are included) with convergence of Poisson solver, but workers fine without coastal shelfs.
I have tried to reduce time steps, but it didn't work :(
Best,
Roman

### CODE REVIEW

**Comment by dionhaefner** [comment]
Sorry, I had already fixed this, but apparently forgot to push the fix :disappointed:

I will push some adjustments soon. Are you sure that we want to stretch the grid so much? It seems a bit aggressive to me, but I haven't compared it to the POP grid.

**Comment by nutrik** [comment]
Markus, told me to make latitude grid with grid step of 0.25 deg. between 6 S and 6 N, and then gradually stretch it towards poles to ~1 deg. resolution. The stretching is done in a way that minimises growing truncation error.

**Comment by nutrik** [comment]
There is one extra thing we need to add to wave propagation case, i.e. the Southern Ocean (SO) wind stress changes by factors 0.5 and 1.5. In total, there will be three cases to run - control, taux(SO)  * 0.5 and taux(SO) * 1.5. 
Could you please add the relevant code below to the next commit?

```
condition = (yt[np.newaxis, :,  np.newaxis]<=-69.) | (yt[np.newaxis, :, np.newaxis]>=-27.)
taux_0p5 = np.where(condition, taux, taux*0.5)
taux_1p5 = np.where(condition, taux, taux*1.5)
taux_0p5[taux_0p5 < 0.] = taux[taux_0p5 < 0.]
taux_1p5[taux_1p5 < 0.] = taux[taux_1p5 < 0.]

from IPython import display
import time
for m in range(12):
    plt.plot(yt, np.mean(taux[...,m], axis=0)) 
    plt.plot(yt, np.mean(taux_0p5[...,m], axis=0))
    plt.plot(yt, np.mean(taux_1p5[...,m], axis=0))
    display.clear_output(wait=True)
    display.display(plt.gcf())
    time.sleep(1.0)
    plt.close()
```

taux

**Comment by dionhaefner** [comment]
I think we should create a separate repository for the actual experiments we want to run. The setups in the Veros repository are mostly meant as templates that can be adapted easily. I will think about how we can set this up in a convenient way.

**Comment by dionhaefner** [comment]
That should do the trick. I changed the grid to the one-sided version of Vinokur's stretching functions and removed the constant part around the equator to achieve a smoother grid. Thanks to the reference to the Vinokur paper, it was really interesting, and I think we have a nice grid toolset now.

Also implemented a switch for the southern ocean winds.

**Pull request merged**
